In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
path = r"C:\DE\test data\HR_Analytics_Messy.csv"   
df = pd.read_csv(path)

In [3]:
df

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,RM212,30.0,26-35,No,Non-Travel,829.0,Research & Development,NaN,1.0,Life Sciences,...,3.0,80.0,0.0,12.0,2.0,NaN,11.0,8.0,5.0,8.0
1,RM606,38.0,36-45,No,Travel_Frequently,471.0,Research & Development,12.0,3.0,Life Sciences,...,3.0,80.0,1.0,13.0,3.0,2.0,4.0,3.0,1.0,2.0
2,RM589,50.0,46-55,No,Travel_Rarely,NaN,Research & Development,2.0,3.0,Medical,...,4.0,80.0,0.0,30.0,3.0,3.0,4.0,3.0,0.0,3.0
3,RM968,40.0,36-45,No,Travel_Rarely,329.0,Research & Development,NaN,4.0,Life Sciences,...,3.0,80.0,1.0,7.0,3.0,3.0,4.0,2.0,0.0,3.0
4,rm1447,34.0,26-35,No,Travel_Rarely,NaN,NaN,NaN,3.0,Marketing,...,4.0,80.0,2.0,8.0,2.0,3.0,8.0,7.0,1.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1525,RM1421,unknown,36-45,No,travel_rarely,NaN,Research & Development,1.0,3.0,Life Sciences,...,1.0,80.0,1.0,12.0,3.0,3.0,5.0,3.0,1.0,0.0
1526,RM168,30.0,26-35,No,Travel_Rarely,unknown,Sales,5.0,3.0,Life Sciences,...,3.0,80.0,1.0,NaN,2.0,3.0,10.0,9.0,7.0,4.0
1527,RM617,unknown,46-55,No,Travel_Rarely,1318.0,Sales,26.0,unknown,Marketing,...,3.0,80.0,1.0,29.0,2.0,2.0,20.0,6.0,4.0,17.0
1528,RM981,31.0,26-35,Yes,Travel_Frequently,703.0,Sales,2.0,3.0,Life Sciences,...,3.0,80.0,NaN,3.0,3.0,4.0,1.0,0.0,0.0,0.0
1529,RM1224,unknown,46-55,Yes,Travel_Frequently,unknown,Sales,9.0,unknown,Life Sciences,...,3.0,80.0,0.0,25.0,3.0,1.0,23.0,5.0,NaN,10.0

In [4]:
df.head()

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,RM212,30.0,26-35,No,Non-Travel,829.0,Research & Development,NaN,1.0,Life Sciences,...,3.0,80.0,0.0,12.0,2.0,NaN,11.0,8.0,5.0,8.0
1,RM606,38.0,36-45,No,Travel_Frequently,471.0,Research & Development,12.0,3.0,Life Sciences,...,3.0,80.0,1.0,13.0,3.0,2.0,4.0,3.0,1.0,2.0
2,RM589,50.0,46-55,No,Travel_Rarely,NaN,Research & Development,2.0,3.0,Medical,...,4.0,80.0,0.0,30.0,3.0,3.0,4.0,3.0,0.0,3.0
3,RM968,40.0,36-45,No,Travel_Rarely,329.0,Research & Development,NaN,4.0,Life Sciences,...,3.0,80.0,1.0,7.0,3.0,3.0,4.0,2.0,0.0,3.0
4,rm1447,34.0,26-35,No,Travel_Rarely,NaN,NaN,NaN,3.0,Marketing,...,4.0,80.0,2.0,8.0,2.0,3.0,8.0,7.0,1.0,7.0

In [5]:
df.shape

(1530, 38)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1530 entries, 0 to 1529
Data columns (total 38 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   EmpID                     1459 non-null   object
 1   Age                       1458 non-null   object
 2   AgeGroup                  1463 non-null   object
 3   Attrition                 1460 non-null   object
 4   BusinessTravel            1461 non-null   object
 5   DailyRate                 1459 non-null   object
 6   Department                1466 non-null   object
 7   DistanceFromHome          1458 non-null   object
 8   Education                 1458 non-null   object
 9   EducationField            1466 non-null   object
 10  EmployeeCount             1459 non-null   object
 11  EmployeeNumber            1453 non-null   float64
 12  EnvironmentSatisfaction   1455 non-null   float64
 13  Gender                    1466 non-null   object
 14  HourlyRate                1454 non-null   float64
 15  JobInvolvement            1450 non-null   float64
 16  JobLevel                  1454 non-null   float64
 17  JobRole                   1464 non-null   object
 18  JobSatisfaction           1450 non-null   float64
 19  MaritalStatus             1460 non-null   object
 20  MonthlyIncome             1455 non-null   float64
 21  SalarySlab                1461 non-null   object
 22  MonthlyRate               1453 non-null   float64
 23  NumCompaniesWorked        1454 non-null   float64
 24  Over18                    1456 non-null   object
 25  OverTime                  1461 non-null   object
 26  PercentSalaryHike         1453 non-null   float64
 27  PerformanceRating         1455 non-null   float64
 28  RelationshipSatisfaction  1452 non-null   float64
 29  StandardHours             1447 non-null   float64
 30  StockOptionLevel          1453 non-null   float64
 31  TotalWorkingYears         1453 non-null   float64
 32  TrainingTimesLastYear     1455 non-null   float64
 33  WorkLifeBalance           1455 non-null   float64
 34  YearsAtCompany            1453 non-null   float64
 35  YearsInCurrentRole        1453 non-null   float64
 36  YearsSinceLastPromotion   1455 non-null   float64
 37  YearsWithCurrManager      1398 non-null   float64
dtypes: float64(21), object(17)
memory usage: 454.3+ KB

In [7]:
df.columns

Index(['EmpID', 'Age', 'AgeGroup', 'Attrition', 'BusinessTravel', 'DailyRate',
       'Department', 'DistanceFromHome', 'Education', 'EducationField',
       'EmployeeCount', 'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender',
       'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobRole',
       'JobSatisfaction', 'MaritalStatus', 'MonthlyIncome', 'SalarySlab',
       'MonthlyRate', 'NumCompaniesWorked', 'Over18', 'OverTime',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StandardHours', 'StockOptionLevel', 'TotalWorkingYears',
       'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany',
       'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [8]:
df.tail()

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1525,RM1421,unknown,36-45,No,travel_rarely,NaN,Research & Development,1.0,3.0,Life Sciences,...,1.0,80.0,1.0,12.0,3.0,3.0,5.0,3.0,1.0,0.0
1526,RM168,30.0,26-35,No,Travel_Rarely,unknown,Sales,5.0,3.0,Life Sciences,...,3.0,80.0,1.0,NaN,2.0,3.0,10.0,9.0,7.0,4.0
1527,RM617,unknown,46-55,No,Travel_Rarely,1318.0,Sales,26.0,unknown,Marketing,...,3.0,80.0,1.0,29.0,2.0,2.0,20.0,6.0,4.0,17.0
1528,RM981,31.0,26-35,Yes,Travel_Frequently,703.0,Sales,2.0,3.0,Life Sciences,...,3.0,80.0,NaN,3.0,3.0,4.0,1.0,0.0,0.0,0.0
1529,RM1224,unknown,46-55,Yes,Travel_Frequently,unknown,Sales,9.0,unknown,Life Sciences,...,3.0,80.0,0.0,25.0,3.0,1.0,23.0,5.0,NaN,10.0

In [9]:
df.isnull().sum()

EmpID                        71
Age                          72
AgeGroup                     67
Attrition                    70
BusinessTravel               69
DailyRate                    71
Department                   64
DistanceFromHome             72
Education                    72
EducationField               64
EmployeeCount                71
EmployeeNumber               77
EnvironmentSatisfaction      75
Gender                       64
HourlyRate                   76
JobInvolvement               80
JobLevel                     76
JobRole                      66
JobSatisfaction              80
MaritalStatus                70
MonthlyIncome                75
SalarySlab                   69
MonthlyRate                  77
NumCompaniesWorked           76
Over18                       74
OverTime                     69
PercentSalaryHike            77
PerformanceRating            75
RelationshipSatisfaction     78
StandardHours                83
StockOptionLevel             77
TotalWorkingYears            77
TrainingTimesLastYear        75
WorkLifeBalance              75
YearsAtCompany               77
YearsInCurrentRole           77
YearsSinceLastPromotion      75
YearsWithCurrManager        132
dtype: int64

checking for duplicate rows

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
text_cols = df.select_dtypes(include='object').columns

for col in text_cols:
    df[col] = df[col].str.strip().str.title()

In [12]:
df.columns

Index(['EmpID', 'Age', 'AgeGroup', 'Attrition', 'BusinessTravel', 'DailyRate',
       'Department', 'DistanceFromHome', 'Education', 'EducationField',
       'EmployeeCount', 'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender',
       'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobRole',
       'JobSatisfaction', 'MaritalStatus', 'MonthlyIncome', 'SalarySlab',
       'MonthlyRate', 'NumCompaniesWorked', 'Over18', 'OverTime',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StandardHours', 'StockOptionLevel', 'TotalWorkingYears',
       'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany',
       'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [13]:
df

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,Rm212,30.0,26-35,No,Non-Travel,829.0,Research & Development,NaN,1.0,Life Sciences,...,3.0,80.0,0.0,12.0,2.0,NaN,11.0,8.0,5.0,8.0
1,Rm606,38.0,36-45,No,Travel_Frequently,471.0,Research & Development,12.0,3.0,Life Sciences,...,3.0,80.0,1.0,13.0,3.0,2.0,4.0,3.0,1.0,2.0
2,Rm589,50.0,46-55,No,Travel_Rarely,NaN,Research & Development,2.0,3.0,Medical,...,4.0,80.0,0.0,30.0,3.0,3.0,4.0,3.0,0.0,3.0
3,Rm968,40.0,36-45,No,Travel_Rarely,329.0,Research & Development,NaN,4.0,Life Sciences,...,3.0,80.0,1.0,7.0,3.0,3.0,4.0,2.0,0.0,3.0
4,Rm1447,34.0,26-35,No,Travel_Rarely,NaN,NaN,NaN,3.0,Marketing,...,4.0,80.0,2.0,8.0,2.0,3.0,8.0,7.0,1.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1525,Rm1421,Unknown,36-45,No,Travel_Rarely,NaN,Research & Development,1.0,3.0,Life Sciences,...,1.0,80.0,1.0,12.0,3.0,3.0,5.0,3.0,1.0,0.0
1526,Rm168,30.0,26-35,No,Travel_Rarely,Unknown,Sales,5.0,3.0,Life Sciences,...,3.0,80.0,1.0,NaN,2.0,3.0,10.0,9.0,7.0,4.0
1527,Rm617,Unknown,46-55,No,Travel_Rarely,1318.0,Sales,26.0,Unknown,Marketing,...,3.0,80.0,1.0,29.0,2.0,2.0,20.0,6.0,4.0,17.0
1528,Rm981,31.0,26-35,Yes,Travel_Frequently,703.0,Sales,2.0,3.0,Life Sciences,...,3.0,80.0,NaN,3.0,3.0,4.0,1.0,0.0,0.0,0.0
1529,Rm1224,Unknown,46-55,Yes,Travel_Frequently,Unknown,Sales,9.0,Unknown,Life Sciences,...,3.0,80.0,0.0,25.0,3.0,1.0,23.0,5.0,NaN,10.0

In [14]:
df = df.replace("Unknown", np.nan)
df = df.replace("unknown", np.nan)

In [15]:
df

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,Rm212,30.0,26-35,No,Non-Travel,829.0,Research & Development,NaN,1.0,Life Sciences,...,3.0,80.0,0.0,12.0,2.0,NaN,11.0,8.0,5.0,8.0
1,Rm606,38.0,36-45,No,Travel_Frequently,471.0,Research & Development,12.0,3.0,Life Sciences,...,3.0,80.0,1.0,13.0,3.0,2.0,4.0,3.0,1.0,2.0
2,Rm589,50.0,46-55,No,Travel_Rarely,NaN,Research & Development,2.0,3.0,Medical,...,4.0,80.0,0.0,30.0,3.0,3.0,4.0,3.0,0.0,3.0
3,Rm968,40.0,36-45,No,Travel_Rarely,329.0,Research & Development,NaN,4.0,Life Sciences,...,3.0,80.0,1.0,7.0,3.0,3.0,4.0,2.0,0.0,3.0
4,Rm1447,34.0,26-35,No,Travel_Rarely,NaN,NaN,NaN,3.0,Marketing,...,4.0,80.0,2.0,8.0,2.0,3.0,8.0,7.0,1.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1525,Rm1421,NaN,36-45,No,Travel_Rarely,NaN,Research & Development,1.0,3.0,Life Sciences,...,1.0,80.0,1.0,12.0,3.0,3.0,5.0,3.0,1.0,0.0
1526,Rm168,30.0,26-35,No,Travel_Rarely,NaN,Sales,5.0,3.0,Life Sciences,...,3.0,80.0,1.0,NaN,2.0,3.0,10.0,9.0,7.0,4.0
1527,Rm617,NaN,46-55,No,Travel_Rarely,1318.0,Sales,26.0,NaN,Marketing,...,3.0,80.0,1.0,29.0,2.0,2.0,20.0,6.0,4.0,17.0
1528,Rm981,31.0,26-35,Yes,Travel_Frequently,703.0,Sales,2.0,3.0,Life Sciences,...,3.0,80.0,NaN,3.0,3.0,4.0,1.0,0.0,0.0,0.0
1529,Rm1224,NaN,46-55,Yes,Travel_Frequently,NaN,Sales,9.0,NaN,Life Sciences,...,3.0,80.0,0.0,25.0,3.0,1.0,23.0,5.0,NaN,10.0

In [16]:
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
num_cols

Index(['EmployeeNumber', 'EnvironmentSatisfaction', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobSatisfaction', 'MonthlyIncome',
       'MonthlyRate', 'NumCompaniesWorked', 'PercentSalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StandardHours',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager'],
      dtype='object')

In [17]:
df.columns

Index(['EmpID', 'Age', 'AgeGroup', 'Attrition', 'BusinessTravel', 'DailyRate',
       'Department', 'DistanceFromHome', 'Education', 'EducationField',
       'EmployeeCount', 'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender',
       'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobRole',
       'JobSatisfaction', 'MaritalStatus', 'MonthlyIncome', 'SalarySlab',
       'MonthlyRate', 'NumCompaniesWorked', 'Over18', 'OverTime',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StandardHours', 'StockOptionLevel', 'TotalWorkingYears',
       'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany',
       'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [18]:
numeric_should_be = [
    'Age', 'DailyRate', 'DistanceFromHome',
    'MonthlyIncome', 'HourlyRate',
    'TotalWorkingYears', 'YearsAtCompany',
    'YearsInCurrentRole', 'YearsSinceLastPromotion',
    'YearsWithCurrManager'
]

In [19]:
for col in numeric_should_be:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1530 entries, 0 to 1529
Data columns (total 38 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   EmpID                     1459 non-null   object
 1   Age                       1382 non-null   float64
 2   AgeGroup                  1463 non-null   object
 3   Attrition                 1460 non-null   object
 4   BusinessTravel            1461 non-null   object
 5   DailyRate                 1383 non-null   float64
 6   Department                1466 non-null   object
 7   DistanceFromHome          1382 non-null   float64
 8   Education                 1382 non-null   object
 9   EducationField            1466 non-null   object
 10  EmployeeCount             1383 non-null   object
 11  EmployeeNumber            1453 non-null   float64
 12  EnvironmentSatisfaction   1455 non-null   float64
 13  Gender                    1466 non-null   object
 14  HourlyRate                1454 non-null   float64
 15  JobInvolvement            1450 non-null   float64
 16  JobLevel                  1454 non-null   float64
 17  JobRole                   1464 non-null   object
 18  JobSatisfaction           1450 non-null   float64
 19  MaritalStatus             1460 non-null   object
 20  MonthlyIncome             1455 non-null   float64
 21  SalarySlab                1461 non-null   object
 22  MonthlyRate               1453 non-null   float64
 23  NumCompaniesWorked        1454 non-null   float64
 24  Over18                    1456 non-null   object
 25  OverTime                  1461 non-null   object
 26  PercentSalaryHike         1453 non-null   float64
 27  PerformanceRating         1455 non-null   float64
 28  RelationshipSatisfaction  1452 non-null   float64
 29  StandardHours             1447 non-null   float64
 30  StockOptionLevel          1453 non-null   float64
 31  TotalWorkingYears         1453 non-null   float64
 32  TrainingTimesLastYear     1455 non-null   float64
 33  WorkLifeBalance           1455 non-null   float64
 34  YearsAtCompany            1453 non-null   float64
 35  YearsInCurrentRole        1453 non-null   float64
 36  YearsSinceLastPromotion   1455 non-null   float64
 37  YearsWithCurrManager      1398 non-null   float64
dtypes: float64(24), object(14)
memory usage: 454.3+ KB

Handling missing values

In [21]:
df.isna()

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,True,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,True,True,True,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1525,False,True,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1526,False,False,False,False,False,True,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
1527,False,True,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
1528,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
1529,False,True,False,False,False,True,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False

In [22]:
df.isna().sum()

EmpID                        71
Age                         148
AgeGroup                     67
Attrition                    70
BusinessTravel               69
DailyRate                   147
Department                   64
DistanceFromHome            148
Education                   148
EducationField               64
EmployeeCount               147
EmployeeNumber               77
EnvironmentSatisfaction      75
Gender                       64
HourlyRate                   76
JobInvolvement               80
JobLevel                     76
JobRole                      66
JobSatisfaction              80
MaritalStatus                70
MonthlyIncome                75
SalarySlab                   69
MonthlyRate                  77
NumCompaniesWorked           76
Over18                       74
OverTime                     69
PercentSalaryHike            77
PerformanceRating            75
RelationshipSatisfaction     78
StandardHours                83
StockOptionLevel             77
TotalWorkingYears            77
TrainingTimesLastYear        75
WorkLifeBalance              75
YearsAtCompany               77
YearsInCurrentRole           77
YearsSinceLastPromotion      75
YearsWithCurrManager        132
dtype: int64

In [23]:
df = df.fillna(0)

In [24]:
df.isna().sum()

EmpID                       0
Age                         0
AgeGroup                    0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
SalarySlab                  0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [25]:
df

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,Rm212,30.0,26-35,No,Non-Travel,829.0,Research & Development,0.0,1.0,Life Sciences,...,3.0,80.0,0.0,12.0,2.0,0.0,11.0,8.0,5.0,8.0
1,Rm606,38.0,36-45,No,Travel_Frequently,471.0,Research & Development,12.0,3.0,Life Sciences,...,3.0,80.0,1.0,13.0,3.0,2.0,4.0,3.0,1.0,2.0
2,Rm589,50.0,46-55,No,Travel_Rarely,0.0,Research & Development,2.0,3.0,Medical,...,4.0,80.0,0.0,30.0,3.0,3.0,4.0,3.0,0.0,3.0
3,Rm968,40.0,36-45,No,Travel_Rarely,329.0,Research & Development,0.0,4.0,Life Sciences,...,3.0,80.0,1.0,7.0,3.0,3.0,4.0,2.0,0.0,3.0
4,Rm1447,34.0,26-35,No,Travel_Rarely,0.0,0,0.0,3.0,Marketing,...,4.0,80.0,2.0,8.0,2.0,3.0,8.0,7.0,1.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1525,Rm1421,0.0,36-45,No,Travel_Rarely,0.0,Research & Development,1.0,3.0,Life Sciences,...,1.0,80.0,1.0,12.0,3.0,3.0,5.0,3.0,1.0,0.0
1526,Rm168,30.0,26-35,No,Travel_Rarely,0.0,Sales,5.0,3.0,Life Sciences,...,3.0,80.0,1.0,0.0,2.0,3.0,10.0,9.0,7.0,4.0
1527,Rm617,0.0,46-55,No,Travel_Rarely,1318.0,Sales,26.0,0,Marketing,...,3.0,80.0,1.0,29.0,2.0,2.0,20.0,6.0,4.0,17.0
1528,Rm981,31.0,26-35,Yes,Travel_Frequently,703.0,Sales,2.0,3.0,Life Sciences,...,3.0,80.0,0.0,3.0,3.0,4.0,1.0,0.0,0.0,0.0
1529,Rm1224,0.0,46-55,Yes,Travel_Frequently,0.0,Sales,9.0,0,Life Sciences,...,3.0,80.0,0.0,25.0,3.0,1.0,23.0,5.0,0.0,10.0

In [26]:
df['Department'] = df['Department'].replace(0, 'Unknown')
df['JobRole'] = df['JobRole'].replace(0, 'Unknown')

In [27]:
df

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,Rm212,30.0,26-35,No,Non-Travel,829.0,Research & Development,0.0,1.0,Life Sciences,...,3.0,80.0,0.0,12.0,2.0,0.0,11.0,8.0,5.0,8.0
1,Rm606,38.0,36-45,No,Travel_Frequently,471.0,Research & Development,12.0,3.0,Life Sciences,...,3.0,80.0,1.0,13.0,3.0,2.0,4.0,3.0,1.0,2.0
2,Rm589,50.0,46-55,No,Travel_Rarely,0.0,Research & Development,2.0,3.0,Medical,...,4.0,80.0,0.0,30.0,3.0,3.0,4.0,3.0,0.0,3.0
3,Rm968,40.0,36-45,No,Travel_Rarely,329.0,Research & Development,0.0,4.0,Life Sciences,...,3.0,80.0,1.0,7.0,3.0,3.0,4.0,2.0,0.0,3.0
4,Rm1447,34.0,26-35,No,Travel_Rarely,0.0,Unknown,0.0,3.0,Marketing,...,4.0,80.0,2.0,8.0,2.0,3.0,8.0,7.0,1.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1525,Rm1421,0.0,36-45,No,Travel_Rarely,0.0,Research & Development,1.0,3.0,Life Sciences,...,1.0,80.0,1.0,12.0,3.0,3.0,5.0,3.0,1.0,0.0
1526,Rm168,30.0,26-35,No,Travel_Rarely,0.0,Sales,5.0,3.0,Life Sciences,...,3.0,80.0,1.0,0.0,2.0,3.0,10.0,9.0,7.0,4.0
1527,Rm617,0.0,46-55,No,Travel_Rarely,1318.0,Sales,26.0,0,Marketing,...,3.0,80.0,1.0,29.0,2.0,2.0,20.0,6.0,4.0,17.0
1528,Rm981,31.0,26-35,Yes,Travel_Frequently,703.0,Sales,2.0,3.0,Life Sciences,...,3.0,80.0,0.0,3.0,3.0,4.0,1.0,0.0,0.0,0.0
1529,Rm1224,0.0,46-55,Yes,Travel_Frequently,0.0,Sales,9.0,0,Life Sciences,...,3.0,80.0,0.0,25.0,3.0,1.0,23.0,5.0,0.0,10.0

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1530 entries, 0 to 1529
Data columns (total 38 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   EmpID                     1530 non-null   object
 1   Age                       1530 non-null   float64
 2   AgeGroup                  1530 non-null   object
 3   Attrition                 1530 non-null   object
 4   BusinessTravel            1530 non-null   object
 5   DailyRate                 1530 non-null   float64
 6   Department                1530 non-null   object
 7   DistanceFromHome          1530 non-null   float64
 8   Education                 1530 non-null   object
 9   EducationField            1530 non-null   object
 10  EmployeeCount             1530 non-null   object
 11  EmployeeNumber            1530 non-null   float64
 12  EnvironmentSatisfaction   1530 non-null   float64
 13  Gender                    1530 non-null   object
 14  HourlyRate                1530 non-null   float64
 15  JobInvolvement            1530 non-null   float64
 16  JobLevel                  1530 non-null   float64
 17  JobRole                   1530 non-null   object
 18  JobSatisfaction           1530 non-null   float64
 19  MaritalStatus             1530 non-null   object
 20  MonthlyIncome             1530 non-null   float64
 21  SalarySlab                1530 non-null   object
 22  MonthlyRate               1530 non-null   float64
 23  NumCompaniesWorked        1530 non-null   float64
 24  Over18                    1530 non-null   object
 25  OverTime                  1530 non-null   object
 26  PercentSalaryHike         1530 non-null   float64
 27  PerformanceRating         1530 non-null   float64
 28  RelationshipSatisfaction  1530 non-null   float64
 29  StandardHours             1530 non-null   float64
 30  StockOptionLevel          1530 non-null   float64
 31  TotalWorkingYears         1530 non-null   float64
 32  TrainingTimesLastYear     1530 non-null   float64
 33  WorkLifeBalance           1530 non-null   float64
 34  YearsAtCompany            1530 non-null   float64
 35  YearsInCurrentRole        1530 non-null   float64
 36  YearsSinceLastPromotion   1530 non-null   float64
 37  YearsWithCurrManager      1530 non-null   float64
dtypes: float64(24), object(14)
memory usage: 454.3+ KB

In [29]:
df['Education'] = pd.to_numeric(df['Education'], errors='coerce')

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1530 entries, 0 to 1529
Data columns (total 38 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   EmpID                     1530 non-null   object
 1   Age                       1530 non-null   float64
 2   AgeGroup                  1530 non-null   object
 3   Attrition                 1530 non-null   object
 4   BusinessTravel            1530 non-null   object
 5   DailyRate                 1530 non-null   float64
 6   Department                1530 non-null   object
 7   DistanceFromHome          1530 non-null   float64
 8   Education                 1530 non-null   float64
 9   EducationField            1530 non-null   object
 10  EmployeeCount             1530 non-null   object
 11  EmployeeNumber            1530 non-null   float64
 12  EnvironmentSatisfaction   1530 non-null   float64
 13  Gender                    1530 non-null   object
 14  HourlyRate                1530 non-null   float64
 15  JobInvolvement            1530 non-null   float64
 16  JobLevel                  1530 non-null   float64
 17  JobRole                   1530 non-null   object
 18  JobSatisfaction           1530 non-null   float64
 19  MaritalStatus             1530 non-null   object
 20  MonthlyIncome             1530 non-null   float64
 21  SalarySlab                1530 non-null   object
 22  MonthlyRate               1530 non-null   float64
 23  NumCompaniesWorked        1530 non-null   float64
 24  Over18                    1530 non-null   object
 25  OverTime                  1530 non-null   object
 26  PercentSalaryHike         1530 non-null   float64
 27  PerformanceRating         1530 non-null   float64
 28  RelationshipSatisfaction  1530 non-null   float64
 29  StandardHours             1530 non-null   float64
 30  StockOptionLevel          1530 non-null   float64
 31  TotalWorkingYears         1530 non-null   float64
 32  TrainingTimesLastYear     1530 non-null   float64
 33  WorkLifeBalance           1530 non-null   float64
 34  YearsAtCompany            1530 non-null   float64
 35  YearsInCurrentRole        1530 non-null   float64
 36  YearsSinceLastPromotion   1530 non-null   float64
 37  YearsWithCurrManager      1530 non-null   float64
dtypes: float64(25), object(13)
memory usage: 454.3+ KB

In [31]:
df['EmployeeCount'].unique()

array(['1.0', 0], dtype=object)

In [32]:
for col in df.select_dtypes(include='object').columns:
    print(col, "→", df[col].unique()[:5])

EmpID → ['Rm212' 'Rm606' 'Rm589' 'Rm968' 'Rm1447']
AgeGroup → ['26-35' '36-45' '46-55' '18-25' '55+']
Attrition → ['No' 'Yes' 0 'Nan']
BusinessTravel → ['Non-Travel' 'Travel_Frequently' 'Travel_Rarely' 'Nan' 'Travelrarely']
Department → ['Research & Development' 'Unknown' 'Sales' 'Nan' 'Human Resources']
EducationField → ['Life Sciences' 'Medical' 'Marketing' 'Other' 'Technical Degree']
EmployeeCount → ['1.0' 0]
Gender → ['Male' 'Female' 'Nan' 0]
JobRole → ['Manufacturing Director' 'Healthcare Representative' 'Research Director'
 'Laboratory Technician' 'Sales Executive']
MaritalStatus → ['Single' 'Divorced' 'Married' 0 'Nan']
SalarySlab → ['5K-10K' '15K+' 'Upto 5K' 0 '10K-15K']
Over18 → ['Y' 0 'Nan']
OverTime → ['No' 'Yes' 0 'Nan']

In [33]:
df = df.replace('Nan', np.nan)
df = df.replace('nan', np.nan)

In [34]:
cat_cols = df.select_dtypes(include='object').columns

for col in cat_cols:
    df[col] = df[col].replace(0, 'Unknown')

In [35]:
df = df.drop(columns=['EmployeeCount'])

In [36]:
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
cat_cols = df.select_dtypes(include='object').columns

In [37]:
df[num_cols] = df[num_cols].fillna(0)          # numeric safe
df[cat_cols] = df[cat_cols].fillna('Unknown')  # categorical safe

In [38]:
df

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,Rm212,30.0,26-35,No,Non-Travel,829.0,Research & Development,0.0,1.0,Life Sciences,...,3.0,80.0,0.0,12.0,2.0,0.0,11.0,8.0,5.0,8.0
1,Rm606,38.0,36-45,No,Travel_Frequently,471.0,Research & Development,12.0,3.0,Life Sciences,...,3.0,80.0,1.0,13.0,3.0,2.0,4.0,3.0,1.0,2.0
2,Rm589,50.0,46-55,No,Travel_Rarely,0.0,Research & Development,2.0,3.0,Medical,...,4.0,80.0,0.0,30.0,3.0,3.0,4.0,3.0,0.0,3.0
3,Rm968,40.0,36-45,No,Travel_Rarely,329.0,Research & Development,0.0,4.0,Life Sciences,...,3.0,80.0,1.0,7.0,3.0,3.0,4.0,2.0,0.0,3.0
4,Rm1447,34.0,26-35,No,Travel_Rarely,0.0,Unknown,0.0,3.0,Marketing,...,4.0,80.0,2.0,8.0,2.0,3.0,8.0,7.0,1.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1525,Rm1421,0.0,36-45,No,Travel_Rarely,0.0,Research & Development,1.0,3.0,Life Sciences,...,1.0,80.0,1.0,12.0,3.0,3.0,5.0,3.0,1.0,0.0
1526,Rm168,30.0,26-35,No,Travel_Rarely,0.0,Sales,5.0,3.0,Life Sciences,...,3.0,80.0,1.0,0.0,2.0,3.0,10.0,9.0,7.0,4.0
1527,Rm617,0.0,46-55,No,Travel_Rarely,1318.0,Sales,26.0,0.0,Marketing,...,3.0,80.0,1.0,29.0,2.0,2.0,20.0,6.0,4.0,17.0
1528,Rm981,31.0,26-35,Yes,Travel_Frequently,703.0,Sales,2.0,3.0,Life Sciences,...,3.0,80.0,0.0,3.0,3.0,4.0,1.0,0.0,0.0,0.0
1529,Rm1224,0.0,46-55,Yes,Travel_Frequently,0.0,Sales,9.0,0.0,Life Sciences,...,3.0,80.0,0.0,25.0,3.0,1.0,23.0,5.0,0.0,10.0

In [39]:
df.loc[df['Age'] == 0, 'Age'] = np.nan
df['Age'] = df['Age'].fillna(df['Age'].median())

In [40]:
df.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1530.000000,1530.000000,1530.000000,1530.000000,1530.000000,1530.00000,1530.000000,1530.000000,1530.000000,1530.000000,...,1530.000000,1530.000000,1530.000000,1530.000000,1530.000000,1530.000000,1530.000000,1530.000000,1530.000000,1530.000000
mean,36.618301,731.561438,8.379739,2.626797,977.266013,2.59281,62.757516,2.586275,1.960131,2.585621,...,2.560131,75.660131,0.752288,10.742484,2.673203,2.622876,6.711765,4.031373,2.087582,3.758824
std,8.663580,449.165168,8.175734,1.294932,632.988121,1.21666,24.518530,0.921764,1.168187,1.235322,...,1.213336,18.126495,0.840099,8.014071,1.395733,0.912596,6.195627,3.657374,3.183331,3.568631
min,18.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,31.000000,350.000000,2.000000,2.000000,422.250000,2.00000,46.000000,2.000000,1.000000,2.000000,...,2.000000,80.000000,0.000000,5.000000,2.000000,2.000000,2.000000,2.000000,0.000000,1.000000
50%,35.000000,720.500000,6.000000,3.000000,968.000000,3.00000,64.000000,3.000000,2.000000,3.000000,...,3.000000,80.000000,1.000000,9.000000,3.000000,3.000000,5.000000,3.000000,1.000000,2.000000
75%,42.000000,1129.500000,12.000000,4.000000,1542.750000,4.00000,83.000000,3.000000,3.000000,4.000000,...,4.000000,80.000000,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,2.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,2068.000000,4.00000,100.000000,4.000000,5.000000,4.000000,...,4.000000,80.000000,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [41]:
df

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,Rm212,30.0,26-35,No,Non-Travel,829.0,Research & Development,0.0,1.0,Life Sciences,...,3.0,80.0,0.0,12.0,2.0,0.0,11.0,8.0,5.0,8.0
1,Rm606,38.0,36-45,No,Travel_Frequently,471.0,Research & Development,12.0,3.0,Life Sciences,...,3.0,80.0,1.0,13.0,3.0,2.0,4.0,3.0,1.0,2.0
2,Rm589,50.0,46-55,No,Travel_Rarely,0.0,Research & Development,2.0,3.0,Medical,...,4.0,80.0,0.0,30.0,3.0,3.0,4.0,3.0,0.0,3.0
3,Rm968,40.0,36-45,No,Travel_Rarely,329.0,Research & Development,0.0,4.0,Life Sciences,...,3.0,80.0,1.0,7.0,3.0,3.0,4.0,2.0,0.0,3.0
4,Rm1447,34.0,26-35,No,Travel_Rarely,0.0,Unknown,0.0,3.0,Marketing,...,4.0,80.0,2.0,8.0,2.0,3.0,8.0,7.0,1.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1525,Rm1421,35.0,36-45,No,Travel_Rarely,0.0,Research & Development,1.0,3.0,Life Sciences,...,1.0,80.0,1.0,12.0,3.0,3.0,5.0,3.0,1.0,0.0
1526,Rm168,30.0,26-35,No,Travel_Rarely,0.0,Sales,5.0,3.0,Life Sciences,...,3.0,80.0,1.0,0.0,2.0,3.0,10.0,9.0,7.0,4.0
1527,Rm617,35.0,46-55,No,Travel_Rarely,1318.0,Sales,26.0,0.0,Marketing,...,3.0,80.0,1.0,29.0,2.0,2.0,20.0,6.0,4.0,17.0
1528,Rm981,31.0,26-35,Yes,Travel_Frequently,703.0,Sales,2.0,3.0,Life Sciences,...,3.0,80.0,0.0,3.0,3.0,4.0,1.0,0.0,0.0,0.0
1529,Rm1224,35.0,46-55,Yes,Travel_Frequently,0.0,Sales,9.0,0.0,Life Sciences,...,3.0,80.0,0.0,25.0,3.0,1.0,23.0,5.0,0.0,10.0

In [42]:



# Fix Education (0 is invalid)

df.loc[df['Education'] == 0, 'Education'] = np.nan
df['Education'] = df['Education'].fillna(df['Education'].median())


# Fix Rating / Scale Columns

rating_cols = [
    'EnvironmentSatisfaction',
    'JobSatisfaction',
    'RelationshipSatisfaction',
    'WorkLifeBalance',
    'JobInvolvement'
]

for col in rating_cols:
    df.loc[df[col] == 0, col] = np.nan
    df[col] = df[col].fillna(df[col].median())


#  EmployeeNumber Handling 
df.loc[df['EmployeeNumber'] == 0, 'EmployeeNumber'] = np.nan
df['EmployeeNumber'] = df['EmployeeNumber'].fillna(method='ffill')


print("Remaining Missing Values →", df.isna().sum().sum())

Remaining Missing Values → 0

C:\Users\rs573\AppData\Local\Temp\ipykernel_18844\1883445497.py:24: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['EmployeeNumber'] = df['EmployeeNumber'].fillna(method='ffill')

In [43]:
df

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,Rm212,30.0,26-35,No,Non-Travel,829.0,Research & Development,0.0,1.0,Life Sciences,...,3.0,80.0,0.0,12.0,2.0,3.0,11.0,8.0,5.0,8.0
1,Rm606,38.0,36-45,No,Travel_Frequently,471.0,Research & Development,12.0,3.0,Life Sciences,...,3.0,80.0,1.0,13.0,3.0,2.0,4.0,3.0,1.0,2.0
2,Rm589,50.0,46-55,No,Travel_Rarely,0.0,Research & Development,2.0,3.0,Medical,...,4.0,80.0,0.0,30.0,3.0,3.0,4.0,3.0,0.0,3.0
3,Rm968,40.0,36-45,No,Travel_Rarely,329.0,Research & Development,0.0,4.0,Life Sciences,...,3.0,80.0,1.0,7.0,3.0,3.0,4.0,2.0,0.0,3.0
4,Rm1447,34.0,26-35,No,Travel_Rarely,0.0,Unknown,0.0,3.0,Marketing,...,4.0,80.0,2.0,8.0,2.0,3.0,8.0,7.0,1.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1525,Rm1421,35.0,36-45,No,Travel_Rarely,0.0,Research & Development,1.0,3.0,Life Sciences,...,1.0,80.0,1.0,12.0,3.0,3.0,5.0,3.0,1.0,0.0
1526,Rm168,30.0,26-35,No,Travel_Rarely,0.0,Sales,5.0,3.0,Life Sciences,...,3.0,80.0,1.0,0.0,2.0,3.0,10.0,9.0,7.0,4.0
1527,Rm617,35.0,46-55,No,Travel_Rarely,1318.0,Sales,26.0,3.0,Marketing,...,3.0,80.0,1.0,29.0,2.0,2.0,20.0,6.0,4.0,17.0
1528,Rm981,31.0,26-35,Yes,Travel_Frequently,703.0,Sales,2.0,3.0,Life Sciences,...,3.0,80.0,0.0,3.0,3.0,4.0,1.0,0.0,0.0,0.0
1529,Rm1224,35.0,46-55,Yes,Travel_Frequently,0.0,Sales,9.0,3.0,Life Sciences,...,3.0,80.0,0.0,25.0,3.0,1.0,23.0,5.0,0.0,10.0

In [44]:
df.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1530.000000,1530.000000,1530.000000,1530.000000,1530.000000,1530.000000,1530.000000,1530.000000,1530.000000,1530.000000,...,1530.000000,1530.000000,1530.000000,1530.000000,1530.000000,1530.000000,1530.000000,1530.000000,1530.000000,1530.000000
mean,36.618301,731.561438,8.379739,2.916993,1029.915033,2.739869,62.757516,2.743137,1.960131,2.742484,...,2.713072,75.660131,0.752288,10.742484,2.673203,2.769935,6.711765,4.031373,2.087582,3.758824
std,8.663580,449.165168,8.175734,0.968590,603.589665,1.066300,24.518530,0.695709,1.168187,1.077306,...,1.060325,18.126495,0.840099,8.014071,1.395733,0.693338,6.195627,3.657374,3.183331,3.568631
min,18.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,...,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,31.000000,350.000000,2.000000,2.000000,491.250000,2.000000,46.000000,2.000000,1.000000,2.000000,...,2.000000,80.000000,0.000000,5.000000,2.000000,2.000000,2.000000,2.000000,0.000000,1.000000
50%,35.000000,720.500000,6.000000,3.000000,1024.500000,3.000000,64.000000,3.000000,2.000000,3.000000,...,3.000000,80.000000,1.000000,9.000000,3.000000,3.000000,5.000000,3.000000,1.000000,2.000000
75%,42.000000,1129.500000,12.000000,4.000000,1561.500000,4.000000,83.000000,3.000000,3.000000,4.000000,...,4.000000,80.000000,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,2.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,2068.000000,4.000000,100.000000,4.000000,5.000000,4.000000,...,4.000000,80.000000,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [45]:
df['EmployeeNumber'] = df['EmployeeNumber'].fillna(method='ffill')

C:\Users\rs573\AppData\Local\Temp\ipykernel_18844\3253373270.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['EmployeeNumber'] = df['EmployeeNumber'].fillna(method='ffill')

In [46]:
df

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,Rm212,30.0,26-35,No,Non-Travel,829.0,Research & Development,0.0,1.0,Life Sciences,...,3.0,80.0,0.0,12.0,2.0,3.0,11.0,8.0,5.0,8.0
1,Rm606,38.0,36-45,No,Travel_Frequently,471.0,Research & Development,12.0,3.0,Life Sciences,...,3.0,80.0,1.0,13.0,3.0,2.0,4.0,3.0,1.0,2.0
2,Rm589,50.0,46-55,No,Travel_Rarely,0.0,Research & Development,2.0,3.0,Medical,...,4.0,80.0,0.0,30.0,3.0,3.0,4.0,3.0,0.0,3.0
3,Rm968,40.0,36-45,No,Travel_Rarely,329.0,Research & Development,0.0,4.0,Life Sciences,...,3.0,80.0,1.0,7.0,3.0,3.0,4.0,2.0,0.0,3.0
4,Rm1447,34.0,26-35,No,Travel_Rarely,0.0,Unknown,0.0,3.0,Marketing,...,4.0,80.0,2.0,8.0,2.0,3.0,8.0,7.0,1.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1525,Rm1421,35.0,36-45,No,Travel_Rarely,0.0,Research & Development,1.0,3.0,Life Sciences,...,1.0,80.0,1.0,12.0,3.0,3.0,5.0,3.0,1.0,0.0
1526,Rm168,30.0,26-35,No,Travel_Rarely,0.0,Sales,5.0,3.0,Life Sciences,...,3.0,80.0,1.0,0.0,2.0,3.0,10.0,9.0,7.0,4.0
1527,Rm617,35.0,46-55,No,Travel_Rarely,1318.0,Sales,26.0,3.0,Marketing,...,3.0,80.0,1.0,29.0,2.0,2.0,20.0,6.0,4.0,17.0
1528,Rm981,31.0,26-35,Yes,Travel_Frequently,703.0,Sales,2.0,3.0,Life Sciences,...,3.0,80.0,0.0,3.0,3.0,4.0,1.0,0.0,0.0,0.0
1529,Rm1224,35.0,46-55,Yes,Travel_Frequently,0.0,Sales,9.0,3.0,Life Sciences,...,3.0,80.0,0.0,25.0,3.0,1.0,23.0,5.0,0.0,10.0

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1530 entries, 0 to 1529
Data columns (total 37 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   EmpID                     1530 non-null   object
 1   Age                       1530 non-null   float64
 2   AgeGroup                  1530 non-null   object
 3   Attrition                 1530 non-null   object
 4   BusinessTravel            1530 non-null   object
 5   DailyRate                 1530 non-null   float64
 6   Department                1530 non-null   object
 7   DistanceFromHome          1530 non-null   float64
 8   Education                 1530 non-null   float64
 9   EducationField            1530 non-null   object
 10  EmployeeNumber            1530 non-null   float64
 11  EnvironmentSatisfaction   1530 non-null   float64
 12  Gender                    1530 non-null   object
 13  HourlyRate                1530 non-null   float64
 14  JobInvolvement            1530 non-null   float64
 15  JobLevel                  1530 non-null   float64
 16  JobRole                   1530 non-null   object
 17  JobSatisfaction           1530 non-null   float64
 18  MaritalStatus             1530 non-null   object
 19  MonthlyIncome             1530 non-null   float64
 20  SalarySlab                1530 non-null   object
 21  MonthlyRate               1530 non-null   float64
 22  NumCompaniesWorked        1530 non-null   float64
 23  Over18                    1530 non-null   object
 24  OverTime                  1530 non-null   object
 25  PercentSalaryHike         1530 non-null   float64
 26  PerformanceRating         1530 non-null   float64
 27  RelationshipSatisfaction  1530 non-null   float64
 28  StandardHours             1530 non-null   float64
 29  StockOptionLevel          1530 non-null   float64
 30  TotalWorkingYears         1530 non-null   float64
 31  TrainingTimesLastYear     1530 non-null   float64
 32  WorkLifeBalance           1530 non-null   float64
 33  YearsAtCompany            1530 non-null   float64
 34  YearsInCurrentRole        1530 non-null   float64
 35  YearsSinceLastPromotion   1530 non-null   float64
 36  YearsWithCurrManager      1530 non-null   float64
dtypes: float64(25), object(12)
memory usage: 442.4+ KB

In [48]:
df.isna().sum()

EmpID                       0
Age                         0
AgeGroup                    0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
SalarySlab                  0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [49]:
output_path = r"C:\DE\test data\HR_Analytics_Final.csv"

df.to_csv(output_path, index=False)

print("Dataset saved successfully")

Dataset saved successfully

In [50]:
path = r"C:\DE\test data\HR_Analytics_Final.csv"
df3= pd.read_csv(path)
df3

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,Rm212,30.0,26-35,No,Non-Travel,829.0,Research & Development,0.0,1.0,Life Sciences,...,3.0,80.0,0.0,12.0,2.0,3.0,11.0,8.0,5.0,8.0
1,Rm606,38.0,36-45,No,Travel_Frequently,471.0,Research & Development,12.0,3.0,Life Sciences,...,3.0,80.0,1.0,13.0,3.0,2.0,4.0,3.0,1.0,2.0
2,Rm589,50.0,46-55,No,Travel_Rarely,0.0,Research & Development,2.0,3.0,Medical,...,4.0,80.0,0.0,30.0,3.0,3.0,4.0,3.0,0.0,3.0
3,Rm968,40.0,36-45,No,Travel_Rarely,329.0,Research & Development,0.0,4.0,Life Sciences,...,3.0,80.0,1.0,7.0,3.0,3.0,4.0,2.0,0.0,3.0
4,Rm1447,34.0,26-35,No,Travel_Rarely,0.0,Unknown,0.0,3.0,Marketing,...,4.0,80.0,2.0,8.0,2.0,3.0,8.0,7.0,1.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1525,Rm1421,35.0,36-45,No,Travel_Rarely,0.0,Research & Development,1.0,3.0,Life Sciences,...,1.0,80.0,1.0,12.0,3.0,3.0,5.0,3.0,1.0,0.0
1526,Rm168,30.0,26-35,No,Travel_Rarely,0.0,Sales,5.0,3.0,Life Sciences,...,3.0,80.0,1.0,0.0,2.0,3.0,10.0,9.0,7.0,4.0
1527,Rm617,35.0,46-55,No,Travel_Rarely,1318.0,Sales,26.0,3.0,Marketing,...,3.0,80.0,1.0,29.0,2.0,2.0,20.0,6.0,4.0,17.0
1528,Rm981,31.0,26-35,Yes,Travel_Frequently,703.0,Sales,2.0,3.0,Life Sciences,...,3.0,80.0,0.0,3.0,3.0,4.0,1.0,0.0,0.0,0.0
1529,Rm1224,35.0,46-55,Yes,Travel_Frequently,0.0,Sales,9.0,3.0,Life Sciences,...,3.0,80.0,0.0,25.0,3.0,1.0,23.0,5.0,0.0,10.0

In [51]:
df3.duplicated().sum()

np.int64(35)

In [52]:
df3['EmpID'].duplicated().sum()

np.int64(132)

In [53]:
df3['EmployeeNumber'].duplicated().sum()

np.int64(134)

In [54]:
df3 = df3.drop_duplicates(subset=['EmpID'], keep='first')

In [55]:
df3['EmpID'].duplicated().sum()

np.int64(0)

In [56]:
df3['EmployeeNumber'].duplicated().sum()

np.int64(70)

In [57]:
df3.shape

(1398, 37)

In [58]:
df3.reset_index(drop=True, inplace=True)

In [59]:
print("Duplicate EmpID:", df3['EmpID'].duplicated().sum())
print("Shape:", df3.shape)

Duplicate EmpID: 0
Shape: (1398, 37)

In [60]:
df3['BusinessTravel'] = (
    df3['BusinessTravel']
        .str.strip()          # removing extra spaces
        .str.lower()          
        .replace({
            'travelrarely': 'travel_rarely',
            'travel rarely': 'travel_rarely'
        })
        .str.title()          
)

C:\Users\rs573\AppData\Local\Temp\ipykernel_18844\1117947654.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['BusinessTravel'] = (

In [61]:
df3['BusinessTravel'].unique()

array(['Non-Travel', 'Travel_Frequently', 'Travel_Rarely', 'Unknown'],
      dtype=object)

In [62]:
output_path = r"C:\DE\test data\HR_Cbi.csv"

df3.to_csv(output_path, index=False)

print("Saved Successfully")

Saved Successfully

In [63]:
check_df = pd.read_csv(output_path)

print("Duplicate EmpID After Reload:", check_df['EmpID'].duplicated().sum())
print("Shape After Reload:", check_df.shape)

Duplicate EmpID After Reload: 0
Shape After Reload: (1398, 37)